# Modelação & Preparação dos Dados

## Configurar Ambiente

In [2]:
import pandas as pd
import os
import sys

## Carregamento de Dados

In [3]:
df = pd.read_csv("../data/Healthcare_dataset.csv")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

## Exploração de Dados

In [4]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [5]:
df.shape
df.columns.tolist()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB

In [6]:
df.head(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

## Limpeza de Dados

### Strings

In [7]:
df["Name"] = df["Name"].str.title()
df["Medical Condition"] = df["Medical Condition"].str.strip().str.title()
df["Doctor"] = df["Doctor"].str.strip().str.title()
df["Hospital"] = df["Hospital"].str.strip().str.title()

### Dates

In [8]:
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"], errors="coerce")
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"], errors="coerce")

In [9]:
df["length_of_stay"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days

### Duplicadas

In [10]:
df.duplicated().sum()

np.int64(534)

In [11]:
df = df.drop_duplicates()

In [12]:
df.duplicated(subset=[
    "Name",
    "Date of Admission",
    "Hospital",
    "Doctor"
]).sum()

np.int64(4966)

In [13]:
df[
    df.duplicated(
        subset=["Name", "Date of Admission", "Hospital", "Doctor"],
        keep=False
    )
].sort_values(by=["Name", "Date of Admission"]).head(20)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,length_of_stay
3040,Aaron Archer,47,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case And Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive,7
54112,Aaron Archer,49,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case And Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive,7
33886,Aaron Carr,59,Female,O-,Asthma,2023-06-20,Diane Davis,"Jones, Holmes Kelley And",Blue Cross,29042.961828,171,Emergency,2023-06-21,Paracetamol,Abnormal,1
51385,Aaron Carr,60,Female,O-,Asthma,2023-06-20,Diane Davis,"Jones, Holmes Kelley And",Blue Cross,29042.961828,171,Emergency,2023-06-21,Paracetamol,Abnormal,1
30468,Aaron Dalton,25,Male,O+,Arthritis,2022-08-22,Sarah Adams,Schroeder Plc,Blue Cross,2070.259477,279,Urgent,2022-09-05,Paracetamol,Inconclusive,14
52721,Aaron Dalton,26,Male,O+,Arthritis,2022-08-22,Sarah Adams,Schroeder Plc,Blue Cross,2070.259477,279,Urgent,2022-09-05,Paracetamol,Inconclusive,14
44720,Aaron Davis,75,Male,O-,Asthma,2023-01-26,John Reyes,Lee-Brown,Blue Cross,23020.208076,339,Urgent,2023-02-04,Ibuprofen,Abnormal,9
55252,Aaron Davis,77,Male,O-,Asthma,2023-01-26,John Reyes,Lee-Brown,Blue Cross,23020.208076,339,Urgent,2023-02-04,Ibuprofen,Abnormal,9
39477,Aaron Fox,81,Male,O-,Arthritis,2022-05-04,Christopher Freeman,"And Vega Gonzales, Coffey",UnitedHealthcare,11269.630146,263,Elective,2022-05-30,Penicillin,Abnormal,26
50385,Aaron Fox,82,Male,O-,Arthritis,2022-05-04,Christopher Freeman,"And Vega Gonzales, Coffey",UnitedHealthcare,11269.630146,263,Elective,2022-05-30,Penicillin,Abnormal,26
40092,Aaron Gates,58,Female,B-,Asthma,2022-11-02,Madeline Ramirez,"Huber Gibson And Bowman,",Medicare,33724.402810,406,Elective,2022-11-27,Aspirin,Inconclusive,25
55339,Aaron Gates,53,Female,B-,Asthma,2022-11-02,Madeline Ramirez,"Huber Gibson And Bowman,",Medicare,33724.402810,406,Elective,2022-11-27,Aspirin,Inconclusive,25
25853,Aaron Harris,29,Male,A-,Hypertension,2023-01-03,Tammy Powell,"Hartman And Larsen, Campos",Aetna,42827.911893,416,Urgent,2023-02-02,Lipitor,Abnormal,30
54637,Aaron Harris,31,Male,A-,Hypertension,2023-01-03,Tammy Powell,"Hartman And Larsen, Campos",Aetna,42827.911893,416,Urgent,2023-02-02,Lipitor,Abnormal,30
21607,Aaron Lee,74,Female,AB-,Arthritis,2020-07-09,Brittany Bryant,Group Mullins,UnitedHealthcare,17042.751715,407,Emergency,2020-07-31,Aspirin,Abnormal,22
50960,Aaron Lee,71,Female,AB-,Arthritis,2020-07-09,Brittany Bryant,Group Mullins,UnitedHealthcare,17042.751715,407,Emergency,2020-07-31,Aspirin,Abnormal,22
49284,Aaron Martinez,33,Male,O+,Cancer,2019-08-27,Carol Smith,Tran Llc,Medicare,23011.552669,126,Emergency,2019-09-15,Paracetamol,Inconclusive,19
52763,Aaron Martinez,36,Male,O+,Cancer,2019-08-27,Carol Smith,Tran Llc,Medicare,23011.552669,126,Emergency,2019-09-15,Paracetamol,Inconclusive,19
38578,Aaron Mason,76,Male,B+,Arthritis,2020-07-23,Cindy Brooks,Bailey-Sandoval,UnitedHealthcare,37264.941645,106,Emergency,2020-07-28,Aspirin,Normal,5
52288,Aaron Mason,73,Male,B+,Arthritis,2020-07-23,Cindy Brooks,Bailey-Sandoval,UnitedHealthcare,37264.941645,106,Emergency,2020-07-28,Aspirin,Normal,5

In [14]:
df_check = df.groupby(
    ["Name", "Date of Admission", "Hospital"]
)["Age"].nunique().reset_index()

df_check[df_check["Age"] > 1].nunique()

Name                 4806
Date of Admission    1724
Hospital             4690
Age                     1
dtype: int64

In [15]:
df = (
    df.sort_values(by="Age")
    .drop_duplicates(
        subset=["Name", "Date of Admission", "Hospital", "Doctor"],
        keep="first"
    )
)

In [16]:
df.describe()

,Age,Date of Admission,Billing Amount,Room Number,Discharge Date,length_of_stay
count,50000.00000,50000,50000.000000,50000.000000,50000,50000.000000
mean,51.42118,2021-11-01 07:31:59.232000,25555.691557,301.032260,2021-11-16 19:32:47.616000,15.500560
min,13.00000,2019-05-08 00:00:00,-2008.492140,101.000000,2019-05-09 00:00:00,1.000000
25%,35.00000,2020-07-28 18:00:00,13239.403094,202.000000,2020-08-13 00:00:00,8.000000
50%,52.00000,2021-11-01 00:00:00,25541.302839,302.000000,2021-11-17 00:00:00,15.000000
75%,68.00000,2023-02-02 00:00:00,37853.996819,400.000000,2023-02-18 00:00:00,23.000000
max,85.00000,2024-05-07 00:00:00,52764.276736,500.000000,2024-06-06 00:00:00,30.000000
std,19.59664,NaN,14215.932247,115.228819,NaN,8.651385

In [17]:
df.duplicated(
    subset=["Name", "Age", "Date of Admission", "Hospital", "Doctor"]
).sum()

np.int64(0)

## Métricas Adicionais

### Duração Internamento

In [ ]:
df["length_of_stay"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

In [ ]:
(df["length_of_stay"] == 0).sum()

np.int64(0)

### Custo por Dia

In [ ]:
df["cost_per_day"] = (
    df["Billing Amount"] / df["length_of_stay"]
)

## Estruturação Modelo

### Dimensões

In [ ]:
d_paciente = df[[
    "Name",
    "Age",
    "Gender",
    "Blood Type"
]]

d_paciente["patient_id"] = range(1, len(d_paciente) + 1)

In [ ]:
d_hospital = df[["Hospital"]].drop_duplicates().reset_index(drop=True)

d_hospital["hospital_id"] = range(1, len(d_hospital) + 1)

In [ ]:
d_doctor = df[["Doctor"]].drop_duplicates().reset_index(drop=True)

d_doctor["doctor_id"] = range(1, len(d_doctor) + 1)

In [ ]:
d_condition = df[["Medical Condition"]].drop_duplicates().reset_index(drop=True)

d_condition["condition_id"] = range(1, len(d_condition) + 1)

In [ ]:
d_admission = df[["Admission Type"]].drop_duplicates().reset_index(drop=True)

d_admission["admission_type_id"] = range(1, len(d_admission) + 1)

In [ ]:
d_insurance = df[["Insurance Provider"]].drop_duplicates().reset_index(drop=True)

d_insurance["insurance_id"] = range(1, len(d_insurance) + 1)

### Fato

In [ ]:
f_internacoes = df.copy()

f_internacoes = f_internacoes.merge(d_paciente, on=["Name", "Age", "Gender", "Blood Type"], how="left")
f_internacoes = f_internacoes.merge(d_hospital, on="Hospital", how="left")
f_internacoes = f_internacoes.merge(d_doctor, on="Doctor", how="left")
f_internacoes = f_internacoes.merge(d_condition, on="Medical Condition", how="left")
f_internacoes = f_internacoes.merge(d_admission, on="Admission Type", how="left")
f_internacoes = f_internacoes.merge(d_insurance, on="Insurance Provider", how="left")

In [ ]:
f_internacoes["internacao_id"] = range(1, len(f_internacoes) + 1)

In [ ]:
f_internacoes.columns.tolist()

['Name',
 'Age',
 'Gender',
 'Blood Type',
 'Medical Condition',
 'admission_date',
 'Doctor',
 'Hospital',
 'Insurance Provider',
 'Billing Amount',
 'Room Number',
 'Admission Type',
 'discharge_date',
 'Medication',
 'Test Results',
 'length_of_stay',
 'cost_per_day',
 'patient_id',
 'hospital_id',
 'doctor_id',
 'condition_id',
 'admission_type_id',
 'insurance_id',
 'internacao_id']

In [45]:
f_internacoes = f_internacoes.rename(columns={
    "Billing Amount": "billing_amount",
    "Room Number": "room_number",
    "Medication": "medication",
    "Test Results": "test_result"
})

In [46]:
f_internacoes = f_internacoes[[
    "internacao_id",
    "patient_id",
    "hospital_id",
    "doctor_id",
    "condition_id",
    "admission_type_id",
    "insurance_id",
    "admission_date",
    "discharge_date",
    "billing_amount",
    "room_number",
    "length_of_stay",
    "cost_per_day",
    "medication",
    "test_result"
]]

## Exportar tabelas

In [47]:
f_internacoes.to_csv("../data/f_internacoes.csv", index=False)
d_paciente.to_csv("../data/d_paciente.csv", index=False)
d_hospital.to_csv("../data/d_hospital.csv", index=False)
d_doctor.to_csv("../data/d_doctor.csv", index=False)
d_condition.to_csv("../data/d_condition.csv", index=False)
d_admission.to_csv("../data/d_admission_type.csv", index=False)
d_insurance.to_csv("../data/d_insurance.csv", index=False)